### ISSUE TITLE
GrinPro 2.1 HiveOS

### ISSUE THREAD

**Issue by MinersRepublic** [mozkomor/GrinProMiner#1]
**I can not start miner on HiveOS. 9 x AMD RX580 Mining SWAP (XWP)**

Miner log:

Shares (sub/acc/stale/rej): 0/0/0/0     Last share:   464 seconds
--------------------------------------------------------------------------------
GPU 0  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 1  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 2  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 3  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 4  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 5  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 6  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 7  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 8  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
--------------------------------------------------------------------------------
                                              Total : 0.00 gps
--------------------------------------------------------------------------------
DEBUG   (sc id 1):TCP IN: {"jsonrpc":"2.o","id":"558982314529898","method":"getjobtemplate","result":{"pre_pow":"0b0b61cdbc5c000000008a02750280e4945187fe0e29a7eafd4bbd5ac8184c3c659438721f889053dbf5d22391cce72faeaecdb2ac0976d25b472162caedc4c9e75b0037761a39d8d647020000000000000000","height":904241,"algo":"cuckaroo","edgebits":29,"proofsize":32,"noncebytes":4,"job_id":"288289650583622","difficulty":1,"id":"558982314529898"}}
DEBUG   (0) PushJobToWorkers: sc id 1, job 288289650583622, job origine user job timestamp 4/21/19 10:06:58 PM
DEBUG   (sc id 1):TCP IN: {"jsonrpc":"2.o","id":"558982314529898","method":"message","result":{"message":"new block at height: 904241"}}
--------------------------------------------------------------------------------
Shares (sub/acc/stale/rej): 0/0/0/0     Last share:   484 seconds
--------------------------------------------------------------------------------
GPU 0  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 1  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 2  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 3  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 4  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 5  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 6  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 7  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 8  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
--------------------------------------------------------------------------------
                                              Total : 0.00 gps
--------------------------------------------------------------------------------
DEBUG   (sc id 1):TCP IN: {"jsonrpc":"2.o","id":"558982314529898","method":"getjobtemplate","result":{"pre_pow":"0b0b72cdbc5c000000004b5e90e0f0d778ada64a6527ee0a84b75a3150b8323c4fad4a9dd9688ac8b2306cf0b5b8fe014a5c6af5247ea2604c9b1813dd888d930fcfc38b8f56a8e38fe2010000000000000000","height":904242,"algo":"cuckaroo","edgebits":29,"proofsize":32,"noncebytes":4,"job_id":"834322631230261","difficulty":1,"id":"558982314529898"}}
DEBUG   (0) PushJobToWorkers: sc id 1, job 834322631230261, job origine user job timestamp 4/21/19 10:07:14 PM
DEBUG   (sc id 1):TCP IN: {"jsonrpc":"2.o","id":"558982314529898","method":"message","result":{"message":"new block at height: 904242"}}
DEBUG   (sc id 1):TCP IN: {"jsonrpc":"2.o","id":"558982314529898","method":"getjobtemplate","result":{"pre_pow":"0b0b75cdbc5c000000003bb13796fe7b858c94e845ca26ff84581096b00ec08940bcf9dd98ced562a67c4b60a7fc53d4103c97551cb2d2cf09135bf06d4d7d4a8f20a62c4b2750b20b90010000000000000000","height":904243,"algo":"cuckaroo","edgebits":29,"proofsize":32,"noncebytes":4,"job_id":"868249569778375","difficulty":1,"id":"558982314529898"}}
DEBUG   (0) PushJobToWorkers: sc id 1, job 868249569778375, job origine user job timestamp 4/21/19 10:07:17 PM
DEBUG   (sc id 1):TCP IN: {"jsonrpc":"2.o","id":"558982314529898","method":"message","result":{"message":"new block at height: 904243"}}
--------------------------------------------------------------------------------
Shares (sub/acc/stale/rej): 0/0/0/0     Last share:   504 seconds
--------------------------------------------------------------------------------
GPU 0  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 1  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 2  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 3  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 4  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 5  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 6  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 7  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
GPU 8  : RX580                STARTING     Mining at  0.00 gps  Solutions: 0
       Last Message: Idle...
--------------------------------------------------------------------------------
                                              Total : 0.00 gps

**Comment by phooton** [comment]
What AMD drivers do you use? ROCm or AMD? Also you can try to run oclsolver executable directly to test the core solver.

**Comment by MinersRepublic** [comment]
AMD 18.10 are preinstalled on HiveOs.

**Comment by phooton** [comment]
This issue was caused by miner thinking it runs on ROCm driver by running rocm-smi command. Hotfix is to rename or move rocm-smi from hive/sbin folder. Next grinpro version will include a permanent fix.

**Comment by MinersRepublic** [comment]
Last version on HiveOs simply doesn't work! Same as before. Are you try miner before post?

**Comment by MinersRepublic** [comment]
starting GrinPro.io miner..
?1h=*******************************************************
HTML Dashboard at http://localhost:5777
JSON API listening on http://localhost:5777/api
         (Both also available over network)
         (API docs: https://grinpro.io/api.html)
*******************************************************
Init started for gpu 0 - RX580
Using OpenCL device: Ellesmere (Advanced Micro Devices, Inc.)

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLOVPI2H3P7I", Request id "0HLOVPI2H3P7I:00000001": An unhandled exception was thrown by the application.
System.TypeLoadException: Could not load type 'SharedSerialization.CuckooType' from assembly 'SharedSerialization, Version=2.7.9717.0, Culture=neutral, PublicKeyToken=null'.
   at GrinProMiner.Controllers.StatusController.Get()
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Init completed for gpu 0 - RX580 with SUCCESS
Init started for gpu 1 - RX580
Using OpenCL device: Ellesmere (Advanced Micro Devices, Inc.)

Init completed for gpu 1 - RX580 with SUCCESS
Init started for gpu 2 - RX580
Using OpenCL device: Ellesmere (Advanced Micro Devices, Inc.)

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLOVPI2H3P7J", Request id "0HLOVPI2H3P7J:00000001": An unhandled exception was thrown by the application.
System.TypeLoadException: Could not load type 'SharedSerialization.CuckooType' from assembly 'SharedSerialization, Version=2.7.9717.0, Culture=neutral, PublicKeyToken=null'.
   at GrinProMiner.Controllers.StatusController.Get()
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Init completed for gpu 2 - RX580 with SUCCESS
Init started for gpu 3 - RX580
Using OpenCL device: Ellesmere (Advanced Micro Devices, Inc.)

Init completed for gpu 3 - RX580 with SUCCESS
Init started for gpu 4 - RX580
Using OpenCL device: Ellesmere (Advanced Micro Devices, Inc.)

Init completed for gpu 4 - RX580 with SUCCESS
Init started for gpu 5 - RX580
Using OpenCL device: Ellesmere (Advanced Micro Devices, Inc.)
